feat: add support for custom NotificationBadge
magicbell-io/magicbell-react pull request #7
Opened 2021-12-03 09:58 UTC by smeijer

> **IMPORTANT** This pull-requests is built upon #6 to reduce the number of merge conflicts. It should be rebased and merged once #6 is merged.

This pull request adds support for a custom notification badge. 

Note that part of this feature is that all the styling for the custom badge is to be added by the custom implementation. That includes the positioning and handling if a `0` value should be rendered or not.

**Example**

```jsx
const badgeStyle = { position: "absolute", top: -4, right: -2, /* … */ };

function NotificationBadge({ count }: { count: number }) {
  if (count === 0) return null;

  return <div style={badgeStyle}>{count}</div>;
}

function MyPage() {
  return (
    <MagicBell NotificationBadge={NotificationBadge} userKey={userKey}>
      {(props) => <Inbox {...props} />}
    </MagicBell>
  );
}
```

2021-12-09 00:23 UTC, josuemontano commented
@smeijer I'm not sure `NotificationBadge` is the best name for this component. Since we export the `Notification` component from this package, someone could got confused and understand that this is a badge for that component. How about `BellBadge`?

2021-12-09 00:27 UTC, josuemontano requested changes

2021-12-09 00:27 UTC, josuemontano commented on src/components/Bell/Bell.tsx
> +  NotificationBadge = BellBadge,
If we expose the `BellBadge` property then we can import this component as `DefaultBellBadge` or something like that to avoid collisions.

2021-12-15 20:46 UTC, smeijer commented on src/components/Bell/Bell.tsx
> +  NotificationBadge = BellBadge,
As talked about on Slack, I've renamed it to `Badge` so it's better matching to `Icon`.

2021-12-15 21:33 UTC, merged