feat: add support for custom NotificationPreferences
magicbell-io/magicbell-react pull request #8
Opened 2021-12-03 13:56 UTC by smeijer

WIP, blocked by #6

2021-12-08 19:23 UTC, smeijer commented on tests/src/components/Header/Header.spec.tsx
> -});
These tests have been moved to the Inbox.

2021-12-08 19:23 UTC, smeijer commented on tests/src/components/Footer/Footer.spec.tsx
> -});
These tests have been moved to the Inbox.

2021-12-09 00:31 UTC, josuemontano commented on tests/src/components/NotificationInbox/NotificationInbox.spec.tsx
> +  screen.getByRole('heading', { name: /notificaciones/i });
Could we please test the casing is correct, too? We don't want to introduce a regression to a bug we fixed some time ago.

2021-12-15 20:23 UTC, smeijer commented on tests/src/components/NotificationInbox/NotificationInbox.spec.tsx
> +  screen.getByRole('heading', { name: /notificaciones/i });
Done. I've made all the affected tests case-sensitive. I'll walk over other test files (that weren't touched by this pull) separately.

2021-12-16 20:33 UTC, josuemontano requested changes

2021-12-16 20:33 UTC, josuemontano commented on src/lib/translations/es.ts
> +    title: 'Notificaciones',
@smeijer We need to revert this for now since some users just want to use lower case for titles. Forcing the style won't work for them until we find a better way to let them override styles.

2021-12-16 20:39 UTC, josuemontano commented on src/components/Header/Header.tsx
> -      <HeaderTitle />
Why are we removing this component? I think this might make us violate the open-closed principle later.

2021-12-16 20:41 UTC, josuemontano commented on src/components/NotificationInbox/NotificationInbox.tsx
> +  const title =
@smeijer please let us move these to their own components

2021-12-16 21:10 UTC, josuemontano commented on src/components/NotificationInbox/NotificationInbox.tsx
> +            <button
Looks like this is a good candidate to be a component of its own, too.

2021-12-16 21:13 UTC, josuemontano commented on src/lib/translations/es.ts
> +    toggle: 'Preferencias de notificación',
Are we missing this translation for `de` and `pt-BR`?

2021-12-16 22:14 UTC, smeijer commented on src/lib/translations/es.ts
> +    toggle: 'Preferencias de notificación',
We are. Should I use Google translate? I'm usually not really comfortable by doing so, because I have no idea if Google is right.

2021-12-17 09:55 UTC, smeijer commented on src/components/Header/Header.tsx
> -      <HeaderTitle />
We don't remove it, we simply inline the styled element. Both `title`, as well as `actions`, accept anything (`ReactNode`) the parent element wishes to render there. I think it promotes extensibility, which is a core part of open-closed.

That being said, I do find it hard to translate the principle to React, as OCP is mostly about OOP while React is more functional. I think it compares best to React component composition.

Do you prefer reverting this change?

2021-12-20 22:50 UTC, josuemontano approved these changes

2021-12-20 22:50 UTC, merged